const influencerData = [
            { id: 'darimi_unni', followers: '21.9만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/darimi_unni_feedImg.jpg', customLink: 'https://www.instagram.com/darimi_unni' },
            { id: 'hamduck2021', followers: '11.1만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/hamduck2021_feedImg.jpg', customLink: 'https://www.instagram.com/hamduck2021' },
            { id: 'onlmom._.ilbo', followers: '7.1만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/onlmom._.ilbo_feedImg.jpg', customLink: 'https://www.instagram.com/onlmom._.ilbo' },
            { id: 'hi.gems_play', followers: '6.8만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/hi.gems_play_feedImg.jpg', customLink: 'https://www.instagram.com/hi.gems_play' },
            { id: 'luvyul_home', followers: '6.5만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/luvyul_home_feedImg.jpg', customLink: 'https://www.instagram.com/luvyul_home' },
            { id: 'yuna_house_', followers: '4.6만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/yuna_house__feedImg.jpg', customLink: 'https://www.instagram.com/yuna_house_' },
            { id: 'minmin_tour', followers: '5.5만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/minmin_tour_feedImg.jpg', customLink: 'https://www.instagram.com/minmin_tour' },
            { id: 'weekndhome', followers: '4.1만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/weekndhome_feedImg.jpg', customLink: 'https://www.instagram.com/weekndhome' },
            { id: 'vivir_ann_', followers: '17.2만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/vivir_ann__feedImg.jpg', customLink: 'https://www.instagram.com/vivir_ann_' },
            { id: 'jiutable', followers: '14만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/jiutable_feedImg.jpg', customLink: 'https://www.instagram.com/jiutable' },
            { id: 'seo_do.a', followers: '11.6만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/seo_do.a_feedImg.jpg', customLink: 'https://www.instagram.com/seo_do.a' },
            { id: '___e.you', followers: '9.4만', profileImg: 'resources/main/influencer/instagram-Icon.png', feedImg: 'resources/main/influencer/feedImg/e.you_feedImg.jpg', customLink: 'https://www.instagram.com/___e.you' }
        ];

const partnerData = [
            { "name": "플랙스 앤 락", "imageUrl": "resources/main/partner-company/플랙스앤락.jpg", "category": "", "description": "생활용품에 재미를 더한 창의적인 인기브랜드"},
            { "name": "퓨처뱅크", "imageUrl": "resources/main/partner-company/퓨처뱅크.jpg", "category": "", "description": "세계최초 앱연동 저금통을 제작한 브랜드"},
            { "name": "티쳐스 과학교구", "imageUrl": "resources/main/partner-company/티쳐스과학교구.jpg", "category": "", "description": "세계 과학교구 브랜드"},
            { "name": "크레아 큐브", "imageUrl": "resources/main/partner-company/크레아큐브.jpg", "category": "", "description": "연산이 가능한 큐브를 제작한 브랜드"},
            { "name": "에스티로더", "imageUrl": "resources/main/partner-company/에스티로더.png", "category": "", "description": "스킨케어, 메이크업, 향수, 헤어케어 등 프레스티지 뷰티 분야에서 세계적인 리더로 자리매김한 글로벌 브랜드"},
            { "name": "팀 브레인즈", "imageUrl": "resources/main/partner-company/팀브레인즈.png", "category": "", "description": "아이들의 교육 학습 능력을 향상시키기 위한 제품을 개발·연구하며,  창의 중심의 교육 솔루션을 제공하는 브랜드"},
            { "name": "티 메디", "imageUrl": "resources/main/partner-company/티메디.png", "category": "", "description": "24가지 유해성분 없이 안전하게 제조하는 구강생활건강 브랜드"},
            { "name": "유이앤루이", "imageUrl": "resources/main/partner-company/유이앤루이.png", "category": "", "description": "사람과 환경을 생각하는 브랜드로 전 제품 코코넛 원료로 제작하는 식기 브랜드"},
            { "name": "티라노 - 주스의 정석", "imageUrl": "resources/main/partner-company/티라노주스의정석.png", "category": "", "description": "물을 첨가하지 않은 100% NFC(비농축) 착즙 주스를 제공하여 소비자에게 건강한 음료의 선택을 제공하는 브랜드"},
            { "name": "잘쓴", "imageUrl": "resources/main/partner-company/잘쓴.png", "category": "", "description": "유해성분 없는 문구를 제작하는 유니크한 국내 브랜드"},
            { "name": "(주)아해교육", "imageUrl": "resources/main/partner-company/아해교육.png", "category": "", "description": "유아 및 초등학생을 위한 창의적 사고력 교육 프로그램과 교구재를 개발·보급하는 대한민국의 교육 콘텐츠 전문 기업"},
            { "name": "유니케어", "imageUrl": "resources/main/partner-company/유니케어.png", "category": "", "description": "친환경 세정제, 전동 분무기, 세탁조 클리너 등 다양한 청소 및 위생 관련 제품을 제조·유통하는 생활용품 브랜드"},
            { "name": "드윈 홈앤리빙", "imageUrl": "resources/main/partner-company/드윈홈앤리빙.png", "category": "", "description": "20년이 넘는 기간 동안 뛰어난 제습효과를 인정받고 있는 프리미엄 제습제를 유통하는 고퀼리티 생활리빙 브랜드"},
            { "name": "블루필", "imageUrl": "resources/main/partner-company/블루필.png", "category": "", "description": "일상 속 익숙한 불편함을 해결하는 데 혁신적인 아이디어와 기술력을 바탕으로 다양한 제품을 개발하는 대한민국의 스마트 소형 가전 전문 기업"},
            { "name": "좋은생활지웰 - 벤투스", "imageUrl": "resources/main/partner-company/좋은생활지웰벤투스.png", "category": "", "description": "실용성과 디자인을 겸비한 생활가전 제품을 통해 소비자들의 일상에 편리함을 더하고자 노력하는 프리미엄 생활가전 브랜드"},
            { "name": "케로스", "imageUrl": "resources/main/partner-company/케로스.png", "category": "", "description": "우수한 기술력과 철저한 서비스 마인드를 바탕으로 최고의 제품을 생산하고 있는 1972년에 설립된 냉난방기 전문 기업"},
            { "name": "밥순삭 꽃게야", "imageUrl": "resources/main/partner-company/밥순삭꽃게야.png", "category": "", "description": "전통적인 제조 방식으로 신선하고 품질 좋은 꽃게를 엄선하여 정성껏 만든 간장게장과 양념게장을 만드는 브랜드"},
            { "name": "100년 보다 깊은 맛", "imageUrl": "resources/main/partner-company/100년보다깊은맛.png", "category": "", "description": "전통의 깊은 맛과 현대적인 편리함을 결합한 대한민국의 프리미엄 식품 브랜드"},
            { "name": "미니덕트", "imageUrl": "resources/main/partner-company/미니덕스.png", "category": "", "description": "특별한 소품을 제작하는 프리미엄 생활 소품 제작 브랜드"},
            { "name": "참새방앗간", "imageUrl": "resources/main/partner-company/참새방앗간.jpg", "category": "", "description": "가족과 함께 간단하게 만드는 송편 키트 제작 브랜드"},
            { "name": "디스띵뜨", "imageUrl": "resources/main/partner-company/디스띵뜨.jpg", "category": "", "description": "처음 기획부터 남다른 학습용품 제작 브랜드(채점색연필)"},
            { "name": "디스톤 유니버스", "imageUrl": "resources/main/partner-company/디스톤유니버스.jpg", "category": "", "description": "탁월하고 유능한 학습유닛을 제작하는 브랜드"},
            { "name": "관찰스쿨", "imageUrl": "resources/main/partner-company/관찰스쿨.jpg", "category": "", "description": "작고 소중한 생명체를 관찰하며 생명의 소중함을 일깨우는 유니크한 교육사업체"},
            { "name": "브레이닝", "imageUrl": "resources/main/partner-company/브레이닝.jpg", "category": "", "description": "색이 변하는 매직우산을 제작하는 브랜드"},
            { "name": "복떡복떡", "imageUrl": "resources/main/partner-company/복떡복떡.jpg", "category": "", "description": "무지개떡 만들기 키트 오색 꽃송편 국산 떡만들기 키드 제작 브랜드"},
            { "name": "밤나무", "imageUrl": "resources/main/partner-company/밤나무.jpg", "category": "", "description": "스페인 감성 유아 악세사리 수입 브랜드"},
            { "name": "망고 슬래브", "imageUrl": "resources/main/partner-company/망고슬래브.jpg", "category": "", "description": "라벨프린터에 AI를 접목시킨 혁신 문구 브랜드"},
            { "name": "리빙디노", "imageUrl": "resources/main/partner-company/리빙다노.jpg", "category": "", "description": "아이디어 생할용품 제작 브랜드"},
            { "name": "딩동에듀", "imageUrl": "resources/main/partner-company/딩동에듀.jpg", "category": "", "description": "아이들의 눈으로 즐겁고 유익한 학습도구를 개발하는 브랜드"},
            { "name": "데일리쉐프", "imageUrl": "resources/main/partner-company/데일리쉐프.jpg", "category": "", "description": "프리미엄 소재만을 사용 하는 깐깐한 플래티넘 주방용품 브랜드"},
            { "name": "이슬라 글로벌", "imageUrl": "resources/main/partner-company/이슬라글로벌.jpg", "category": "", "description": "유니크한 디자인과 칼라에 안전성까지 더한 유아동 놀이용품 수입 브랜드"}
        ];