        const category = [
            {"name": "child-edu", "content": "유아 / 교육"},
            {"name": "living", "content": "리빙 / 라이프스타일"},
            {"name": "home-appliance", "content": "가전"},
            {"name": "food", "content": "식품"}
        ];

        const product = [
            { "name": "[정품] 글리너 수동 보풀제거기", "imageUrl": "resources/product/living/글리너.png", "category": "living", "companyName": "Gleener", "description": "✔️ 캐나다 프리미엄 의류관리브랜드\n ✔️ 옷감손상없는 보풀제거기\n ✔️ 누적매출 50억 \n ✔️ 메이저 3사 홈쇼핑 런칭 \n ✔️ 누적 공동구매 매출 20억"},
            { "name": "세탁볼", "imageUrl": "resources/product/child-edu/세탁볼.jpg", "category": "living", "companyName": ""},
            { "name": "계량스푼", "imageUrl": "resources/product/child-edu/데일리셰프.jpg", "category": "living", "companyName": "데일리셰프"},
            { "name": "중식도", "imageUrl": "resources/product/child-edu/데일리셰프2.jpg", "category": "living", "companyName": "데일리셰프"},
            { "name": "올스텐가위", "imageUrl": "resources/product/child-edu/올스텐가위.jpg", "category": "living", "companyName": ""},
            { "name": "리빙디노미끄럼방지제", "imageUrl": "resources/product/child-edu/리빙디노미끄럼방지제.jpg", "category": "living", "companyName": ""},
            { "name": "실리콘뒤집개", "imageUrl": "resources/product/child-edu/실리콘뒤집개.jpg", "category": "living", "companyName": ""},

            { "name": "AI보드게임", "imageUrl": "resources/product/child-edu/AI보드게임.jpg", "category": "child-edu", "companyName": ""},
            { "name": "개미키우기", "imageUrl": "resources/product/child-edu/개미키우기.jpg", "category": "child-edu", "companyName": ""},
            { "name": "낚시놀이세트", "imageUrl": "resources/product/child-edu/낚시놀이세트.jpg", "category": "child-edu", "companyName": ""},
            { "name": "네모닉AI프린터", "imageUrl": "resources/product/child-edu/네모닉AI프린터.jpg", "category": "child-edu", "companyName": "nemonic"},
            { "name": "에어로켓", "imageUrl": "resources/product/child-edu/네셔널지오그래픽-에어로켓.jpg", "category": "child-edu", "companyName": "네셔널지오그래픽"},
            { "name": "눌러쓰는색연필", "imageUrl": "resources/product/child-edu/눌러쓰는색연필.jpg", "category": "child-edu", "companyName": ""},
            { "name": "다이슨헤어장난감", "imageUrl": "resources/product/child-edu/다이슨헤어장난감.jpg", "category": "child-edu", "companyName": ""},
            { "name": "당기면나타나는입체도형", "imageUrl": "resources/product/child-edu/당기면나타나는입체도형.jpg", "category": "child-edu", "companyName": ""},
            { "name": "수학 학습도우미 점착 메모지", "imageUrl": "resources/product/child-edu/디스띵뜨.jpg", "category": "child-edu", "companyName": "디스띵뜨"},
            { "name": "디얼키링캠", "imageUrl": "resources/product/child-edu/디얼키링캠.jpg", "category": "child-edu", "companyName": ""},
            { "name": "똑똑꾸러밍 과학교구", "imageUrl": "resources/product/child-edu/똑똑꾸러밍1.jpg", "category": "child-edu", "companyName": "똑똑꾸러밍"},
            { "name": "똑똑꾸러밍 과학교구", "imageUrl": "resources/product/child-edu/똑똑꾸러밍2.jpg", "category": "child-edu", "companyName": "똑똑꾸러밍"},
            { "name": "똑똑꾸러밍 과학교구", "imageUrl": "resources/product/child-edu/똑똑꾸러밍3.jpg", "category": "child-edu", "companyName": "똑똑꾸러밍"},
            { "name": "똑똑꾸러밍스노우볼", "imageUrl": "resources/product/child-edu/똑똑꾸러밍스노우볼.jpg", "category": "child-edu", "companyName": ""},
            { "name": "러시이스케이프", "imageUrl": "resources/product/child-edu/러시이스케이프.jpg", "category": "child-edu", "companyName": ""},
            { "name": "루비베인", "imageUrl": "resources/product/child-edu/루비베인.jpg", "category": "child-edu", "companyName": ""},
            { "name": "리틀빈학습카드", "imageUrl": "resources/product/child-edu/리틀빈학습카드.jpg", "category": "child-edu", "companyName": ""},
            { "name": "마그네틱큐브", "imageUrl": "resources/product/child-edu/마그네틱큐브.jpg", "category": "child-edu", "companyName": ""},
            { "name": "마시멜로허니팟", "imageUrl": "resources/product/child-edu/마시멜로허니팟.jpg", "category": "child-edu", "companyName": ""},
            { "name": "멀티펀치슬라이더", "imageUrl": "resources/product/child-edu/멀티펀치슬라이더.jpg", "category": "child-edu", "companyName": ""},
            { "name": "메타블록스", "imageUrl": "resources/product/child-edu/메타블록스.jpg", "category": "child-edu", "companyName": ""},
            { "name": "모래놀이세트", "imageUrl": "resources/product/child-edu/모래놀이세트.jpg", "category": "child-edu", "companyName": ""},
            { "name": "미니자석블럭", "imageUrl": "resources/product/child-edu/미니자석블럭.jpg", "category": "child-edu", "companyName": ""},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모1.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모2.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모3.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모4.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모5.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모6.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모7.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모8.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "미니쿄모 손목 시계", "imageUrl": "resources/product/child-edu/미니쿄모9.jpg", "category": "child-edu", "companyName": "미니쿄모"},
            { "name": "바나나맛우유골프네임텍", "imageUrl": "resources/product/child-edu/바나나맛우유골프네임텍.jpg", "category": "child-edu", "companyName": ""},
            { "name": "바나나맛우유볼마커", "imageUrl": "resources/product/child-edu/바나나맛우유볼마커.jpg", "category": "child-edu", "companyName": ""},
            { "name": "바나나맛우유티꽂이세트", "imageUrl": "resources/product/child-edu/바나나맛우유티꽂이세트.jpg", "category": "child-edu", "companyName": ""},
            { "name": "브레인쉐입스", "imageUrl": "resources/product/child-edu/브레인쉐입스.jpg", "category": "child-edu", "companyName": ""},
            { "name": "블루래빗산리오", "imageUrl": "resources/product/child-edu/블루래빗산리오.jpg", "category": "child-edu", "companyName": ""},
            { "name": "블루래빗첫놀잇감", "imageUrl": "resources/product/child-edu/블루래빗첫놀잇감.jpg", "category": "child-edu", "companyName": ""},
            { "name": "빙그레볼마커", "imageUrl": "resources/product/child-edu/빙그레볼마커.jpg", "category": "child-edu", "companyName": ""},
            { "name": "스마일게키우기", "imageUrl": "resources/product/child-edu/스마일게키우기.jpg", "category": "child-edu", "companyName": ""},
            { "name": "스피로그래프", "imageUrl": "resources/product/child-edu/스피로그래프.jpg", "category": "child-edu", "companyName": ""},
            { "name": "아기독서대", "imageUrl": "resources/product/child-edu/아기독서대.jpg", "category": "child-edu", "companyName": ""},
            { "name": "아트란포켓프린트카메라", "imageUrl": "resources/product/child-edu/아트란포켓프린트카메라.jpg", "category": "child-edu", "companyName": ""},
            { "name": "아피토코딩로봇", "imageUrl": "resources/product/child-edu/아피토코딩로봇.jpg", "category": "child-edu", "companyName": ""},
            { "name": "어린이휴대용현미경", "imageUrl": "resources/product/child-edu/어린이휴대용현미경.jpg", "category": "child-edu", "companyName": ""},
            { "name": "엔그로운", "imageUrl": "resources/product/child-edu/엔그로운.jpg", "category": "child-edu", "companyName": ""},
            { "name": "올붓지구본", "imageUrl": "resources/product/child-edu/올붓지구본.jpg", "category": "child-edu", "companyName": ""},
            { "name": "자석블럭", "imageUrl": "resources/product/child-edu/자석블럭.jpg", "category": "child-edu", "companyName": ""},
            { "name": "자석칠교", "imageUrl": "resources/product/child-edu/자석칠교.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잘잘리오", "imageUrl": "resources/product/child-edu/잘잘리오.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잼바라1", "imageUrl": "resources/product/child-edu/잼바라1.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잼바라2", "imageUrl": "resources/product/child-edu/잼바라2.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잼바라3", "imageUrl": "resources/product/child-edu/잼바라3.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잼바라4", "imageUrl": "resources/product/child-edu/잼바라4.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잼바라5", "imageUrl": "resources/product/child-edu/잼바라5.jpg", "category": "child-edu", "companyName": ""},
            { "name": "잼바라6", "imageUrl": "resources/product/child-edu/잼바라6.jpg", "category": "child-edu", "companyName": ""},
            { "name": "집중력학습기슐터", "imageUrl": "resources/product/child-edu/집중력학습기슐터.jpg", "category": "child-edu", "companyName": ""},
            { "name": "칠교", "imageUrl": "resources/product/child-edu/칠교.jpg", "category": "child-edu", "companyName": ""},
            { "name": "크레아큐브", "imageUrl": "resources/product/child-edu/크레아큐브.jpg", "category": "child-edu", "companyName": ""},
            { "name": "택토닥터", "imageUrl": "resources/product/child-edu/택토닥터.jpg", "category": "child-edu", "companyName": ""},
            { "name": "택토체스", "imageUrl": "resources/product/child-edu/택토체스.jpg", "category": "child-edu", "companyName": ""},
            { "name": "퓨쳐뱅크삐뽀", "imageUrl": "resources/product/child-edu/퓨쳐뱅크삐뽀.jpg", "category": "child-edu", "companyName": ""},
            { "name": "플레이시푸", "imageUrl": "resources/product/child-edu/플레이시푸.jpg", "category": "child-edu", "companyName": ""},
            { "name": "픽시케이드", "imageUrl": "resources/product/child-edu/픽시케이드.jpg", "category": "child-edu", "companyName": ""},
            
            { "name": "쥬스의정석", "imageUrl": "resources/product/child-edu/쥬스의정석.jpg", "category": "food", "companyName": ""},
            { "name": "쥬스의정석", "imageUrl": "resources/product/child-edu/쥬스의정석2.jpg", "category": "food", "companyName": ""},
            { "name": "쥬스의정석", "imageUrl": "resources/product/child-edu/쥬스의정석3.jpg", "category": "food", "companyName": ""},
            { "name": "쥬스의정석", "imageUrl": "resources/product/child-edu/쥬스의정석4.jpg", "category": "food", "companyName": ""},
            { "name": "무무쮸", "imageUrl": "resources/product/child-edu/무무쮸.jpg", "category": "food", "companyName": ""},
            { "name": "백년보다깊은냉면", "imageUrl": "resources/product/child-edu/백년보다깊은냉면.jpg", "category": "food", "companyName": ""},
            { "name": "넛디넛스프레드", "imageUrl": "resources/product/child-edu/넛디넛스프레드.jpg", "category": "food", "companyName": "NUTDY NUT"},
            { "name": "넛디바", "imageUrl": "resources/product/child-edu/넛디뱌.jpg", "category": "food", "companyName": "NUTDY NUT"},
            
            { "name": "듀얼가습기", "imageUrl": "resources/product/child-edu/듀얼가습기.jpg", "category": "home-appliance", "companyName": "블루필"},
            { "name": "아트란 큐패드", "imageUrl": "resources/product/child-edu/가성비테블릿.jpg", "category": "home-appliance", "companyName": ""},
            { "name": "캐로스무선선풍기", "imageUrl": "resources/product/child-edu/캐로스무선선풍기.jpg", "category": "home-appliance", "companyName": ""}
        ];

